apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mirmicode
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: mirmicode-tailscale-entrypoint
    files:
      - ts-entrypoint.sh
    options:
      disableNameSuffixHash: true
  - name: mirmicode-caddy
    files:
      - Caddyfile.template
    options:
      disableNameSuffixHash: true
